### PR TITLE
add x-accel location to nginx config

### PR DESCRIPTION
**Pull request by snopoke**
@benrudolph @TylerSheffels

### CODE REVIEW

**Comment by dannyroberts** [comment]
Not sure I understand. What are we using x-accel (http://wiki.nginx.org/X-accel) for and how does this do that?

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/6615

**Comment by snopoke** [comment]
I haven't tested this yet, will give it a whirl next week

**Comment by snopoke** [comment]
@benrudolph @TylerSheffels I tested this locally and it works

**Pull request merged**
