### PR TITLE
Add MOTECH Test Servers to Nginx Proxy

### PR DESCRIPTION
**Pull request by sheelio**
For this ticket:
http://manage.dimagi.com/default.asp?187743

### CODE REVIEW

**Comment by sheelio** [comment]
@orangejenny @esoergel @nickpell 
Ansible changes to add a motech test servers to our proxy

**Comment by esoergel** [comment]
I think I'm gonna defer to @dannyroberts and @TylerSheffels on this one.

**Comment by TylerSheffels** [comment]
@sheelio Looks good to me.

The other steps we need here are:
[] Update the config repo on prod, staging, india to include these options in the available sites
[] Add DNS entries for each of these
[] Actually deploy (do you have someone in mind @sheelio?)

**Comment by sheelio** [comment]
i've added the DNS entries already.  And the servers are all setup.  If these changes look good, I think good for anyone deploy. 

(Not sure what the config repo is?)

**Comment by benrudolph** [comment]
@sheelio crushing it.

sheel the config repo is on our "salt" machine which is where we do the deploys from. the person who will be deploying this should know what that means (no action on your part)

**Comment by TylerSheffels** [comment]
@sheelio Second Ben's "Crushing is comment" I am deploying this now so should be ready shortly.

**Pull request merged**
