### PR TITLE
Route formplayer requests based on sessionid

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @dannyroberts ok so here's one option we talked about. Not positive it'll work, but this'll require formplayer to make all its requests like `/formplayer/my-domain/my-username` then it'll get proxied to the the `formplayer` upstream and be balanced with `hash $request_uri consistent` which will then hash based on domain and username. _hopefully_ this'll mean that data is divided equally among all servers that we have. and we can then avoid using the nfs and store directly on `/opt/data`, the encrypted drive

### CODE REVIEW

**Comment by benrudolph** [comment]
https://github.com/dimagi/commcare-hq/pull/13080

**Comment by benrudolph** [comment]
waaayyy simpler to just hash based on the sessionid in cookie. thanks @dannyroberts!

**Comment by benrudolph** [comment]
✔️ works on staging

**Comment by dannyroberts** [comment]
nice work! This is maybe the simplest "turn on scale" PR I've ever seen.

**Comment by benrudolph** [comment]
haha it was a windy road!

**Comment by dannyroberts** [comment]
OK, merging it! ⚡

**Pull request merged**
