### PR TITLE
Purge old restore files

### PR DESCRIPTION
**Pull request by benrudolph**
Note, this is dependent on this PR: https://github.com/dimagi/commcare-hq/pull/5956

@TylerSheffels

### CODE REVIEW

**Comment by czue** [comment]
i'll let @TylerSheffels or @dannyroberts review, but i think it's fine to merge this before https://github.com/dimagi/commcare-hq/pull/5956

**Comment by dannyroberts** [comment]
Sweet, @benrudolph! What machine do you want this deployed to? Django workers? I think it'd make sense to either make a new role for this or add it to a role that only gets deployed to the inventory group you're targeting.

**Comment by benrudolph** [comment]
hmm not too sure. i'm assuming it'd have to be deployed to all machines which run the application so i'm guessing that'd be django workers? is that the `webworker` role? makes sense to only deploy to that. let me know if we have that role (not too familiar with the setup), else i'll make a new one

**Comment by dannyroberts** [comment]
Yeah, so https://github.com/dimagi/commcarehq-ansible/blob/64f0be510930ef74f53224dd9c72de6a3a043a37/ansible/deploy_webworker.yml is the entrypoint for things that run only on webworkers (the line `hosts: webworkers` is say, run these roles on the `webworkers` inventory group).

**Comment by dannyroberts** [comment]
You can either add to the `webworkers` role, or add your own role ('commcaresync' or whatever) and make sure to reference that from this file.

**Comment by benrudolph** [comment]
thanks for the pointers, will look today

**Comment by benrudolph** [comment]
Decided to just add the task to the `webworker` role since it seemed like overkill to make an entirely new role for one minor cron job

**Comment by dannyroberts** [comment]
Ok, sounds good!

**Comment by benrudolph** [comment]
@dannyroberts i think this is now good to go

**Comment by dannyroberts** [comment]
Awesome! Thanks for being persistent in working out the kinks!

**Comment by snopoke** [comment]
Nice

**Pull request merged**
