### PR TITLE
fix couchdb2 requirement

### PR DESCRIPTION
**Pull request by javierwilson**
:( had the wrong repo
@mkangia thisis important to fix and do a  ansible-galaxy install --force

### CODE REVIEW

**Comment by javierwilson** [comment]
@emord actually the problem is (i think) that the couchdb-cluster repo requires the couchdb repo, but not the latest one, so it keeps pulling the one which doesn't create the parent dir :( We can get around it, re-installing the appropiate couchdb repo manually. or fixing this in your repo.

**Comment by emord** [comment]
@javierwilson I think we could also require the both repositories in our requirements yml?

**Comment by javierwilson** [comment]
yes, as long as we require the cloudb-cluster repo first, it will work, still a force install is required. testing and commiting...

**Comment by javierwilson** [comment]
@emord this fixes the requirements issue, there's still an issue regarding the data directory not existing, but that will go in a different PR

**Comment by emord** [comment]
@javierwilson ah. i think I know what happened with the data directory. originally I had the data directory created by the ansible task, but the maintainer asked me to put it in the init script. I removed that when I discovered that that would create the directory even if the encrypted drive wasn't mounted. I probably didn't add that back to the ansible task.

**Pull request merged**
