### PR TITLE
Use riakcs swap for postgres too

### PR DESCRIPTION
**Pull request by kaapstorm**
Would this work, @benrudolph @snopoke ? (I have not tested this!)

### CODE REVIEW

**Comment by kaapstorm** [comment]
Yes.

**Comment by benrudolph** [comment]
my preference for this would be to just selectively add swap to the machines we need. don't think it's great to rely on swap. that said not super convinced it matters that much

**Comment by snopoke** [comment]
+1 to only have this on machines we want. I haven't looked closely but this might only get applied to hosts with the `swap_size` var set (which gets set in inventory).

**Comment by emord** [comment]
closing this out because https://github.com/dimagi/commcarehq-ansible/pull/706 likely supersedes it

**Pull request closed without merging**
