### PR TITLE
formplayer needs couch-users db

### PR DESCRIPTION
**Pull request by sravfeyn**

### CODE REVIEW

**Comment by snopoke** [comment]
This should work for ICDS but won't for any other ENV's since `couchdbs.users` won't exist. We probably have to add another setting telling ansible which CouchDB should be used by Formplayer:
```
couchdbs[formplayer_couchdb].host
```

**Comment by sravfeyn** [comment]
@snopoke I have updated rest of env settings to have `couchdb.users` and point by default to the default db. Is this better.

**Comment by dannyroberts** [comment]
Did we end up needing this, or should we close?

**Comment by sravfeyn** [comment]
Probably not needed, thanks for pinging Danny!

**Pull request closed without merging**
