### PR TITLE
postgresql_ssl_enabled defaults to False

### PR DESCRIPTION
**Pull request by nickpell**
based on discussion with @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
:+1: maybe @dannyroberts to confirm?

**Comment by dannyroberts** [comment]
I'm not super familiar with what changing `postgresql_ssl_enabled` does on a production environment. Can you describe what'll happen when we deploy this to prod?

**Comment by benrudolph** [comment]
postgres will stop using ssl for connections to it over the network if this is set to false. but i believe that's already the case on prod. https://dimagi.slack.com/archives/web-team/p1459324647000130

**Comment by dannyroberts** [comment]
Cool, thanks. Let's make sure to run this with `--check` on each instance we have to make sure we're either not changing things or changing things correctly. (I imagine there's a change that needs to happen on both postgres clients like web workers, etc. and in postgres's config itself.)

Good to merge from my side once you've removed the hold off on merge tag.

**Pull request merged**
