### PR TITLE
enable datadog on ICDS

### PR DESCRIPTION
**Pull request by snopoke**
Should roll this out to a single server first to test.

FYI @benrudolph @sravfeyn 
buddy @mkangia

### CODE REVIEW

**Comment by snopoke** [comment]
@dimagi/scale-team

**Comment by sravfeyn** [comment]
`datadog_enabled` should be updated on `icds_public.yml`

**Comment by snopoke** [comment]
@sravfeyn do you mean this: https://github.com/dimagi/commcarehq-ansible/pull/643/files#diff-2a475a69e9f47422e69d6e420532df87R153

**Comment by snopoke** [comment]
more here: https://github.com/dimagi/commcarehq-ansible/pull/644

**Pull request merged**
