### PR TITLE
Install ranger and kafkat

### PR DESCRIPTION
**Pull request by esoergel**
ranger everywhere and kafkat on kafka machines
@benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
:beetle: :cat:

**Comment by benrudolph** [comment]
:+1: on :white_check_mark:

**Comment by czue** [comment]
what do these do?

**Comment by benrudolph** [comment]
@esoergel can probably give you more of an explanation, but from my discussion with him, `kafkat` is a command line utility for working with kafka since kafka's mgmt via the command line is very difficult

**Comment by esoergel** [comment]
Yup, kafkat is a cmdline kafka tool.  I found it very difficult to see what's going on with a kafka cluster (see my [migration notes](https://confluence.dimagi.com/display/internal/Migrating+a+Kafka+cluster) for examples), and kafkat looks much more manageable.

Ranger is a command line file browser.  I could totally be talked out of it if we're concerned about bloat, but I find it very useful.  Basically it lets you move through files and directories much more easily than `cd` and `ls`.

**Comment by czue** [comment]
:+1: doesn't bother me, was just wondering in case they were useful (sounds like they are)

**Pull request merged**
