### PR TITLE
devreadonly user

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke i couldn't find anywhere where we actually set this user up. i went through some iterations on this to try and get it right. still trying to figure out why i'm only able to read from some tables

cc: @wpride @orangejenny

### CODE REVIEW

**Comment by snopoke** [comment]
You should take a look at this: https://github.com/dimagi/commcarehq-ansible/pull/380/files#diff-ca3206fc1d7501d5550eed5478ab055fR120

This also described it quite well: http://stackoverflow.com/a/762649

**Comment by benrudolph** [comment]
ah great thanks!

**Comment by benrudolph** [comment]
man can't believe i missed that

**Comment by snopoke** [comment]
I think that PR hasn't been merged because it contains some Ansible 2.0
stuff. @sravfeyn might recall exactly what.

**Comment by sravfeyn** [comment]
Yeah, that PR is supposed to manage various pg user and db creation, and permissions via a user-db-permission mapping config. It needs Ansible2.0. I didn't prioritize it as it was not needed for ICDS, yet. 

That PR is more general purpose than this, but I am fine with having this merged for now.

**Comment by benrudolph** [comment]
closing for now as this is no longer blocking formplayer and seems the work in the other PR is the better route

**Pull request closed without merging**
