### PR TITLE
Refactor restore payload

### PR DESCRIPTION
**Pull request by benrudolph**
Don't think we need this `java` dependency anymore

@dannyroberts

### CODE REVIEW

**Comment by benrudolph** [comment]
It allows the cchq user to write to the folder since nogroup anonymous id is changed to 1500 (that was set in the other PR). So nogroup is effectively the `nfs` group. I have no idea why it doesn't work to just set the group as `nfs`. I have no idea why that isn't essentially the same thing, but it fails on the `chown` when I try it

**Comment by dannyroberts** [comment]
Is it possible for the files themselves to be owned by the nfs group? Or do those also get written as nobody:nogroup?

**Comment by benrudolph** [comment]
they get written as nobody:nogroup when written by the `cchq` user on the client machiens

**Comment by benrudolph** [comment]
i believe, if you are the host machine you can own the files as `nfs`

**Comment by dannyroberts** [comment]
Interesting. Well, thanks for the explanation and for digging into all this!

**Pull request merged**
