### PR TITLE
Fix DHIS2 Reporting Correct Server URL on motech1/motech2

### PR DESCRIPTION
**Pull request by sheelio**
@TylerSheffels I think this is the correct configuration.  I copied:
https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/nginx/vars/motech.yml

### CODE REVIEW

**Comment by TylerSheffels** [comment]
@sheelio Want me to deploy these changes?

**Comment by sheelio** [comment]
@TylerSheffels Yup, if you can deploy these, that would be great.

**Comment by TylerSheffels** [comment]
@sheelio Ok, its deployed now.

**Comment by sheelio** [comment]
@TylerSheffels 

Ah crap, these changes don't work.  Everything keeps redirecting to the base URL. 
https://test-endos-motech.commcarehq.org/dhis auto redirects to https://test-endos-motech.commcarehq.org

Is there something I missed up in the configuration?

**Pull request merged**
