### PR TITLE
add ucrreadonly in pg_hba

### PR DESCRIPTION
**Pull request by sravfeyn**

### CODE REVIEW

**Comment by sravfeyn** [comment]
@TylerSheffels

**Comment by czue** [comment]
@sravfeyn I think you need to also add code that creates this user if you want to roll this out globally

**Comment by czue** [comment]
(will let @TylerSheffels @dannyroberts or @benrudolph confirm)

**Comment by sravfeyn** [comment]
I was trying to find way to create the user globally in all environments, but couldn't find it easily. So I manually created it for india as it was urgent.

Any pointers to have ansible create this user? I found the task [here](https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/postgresql/tasks/main.yml#L91) but couldn't figure where to put the new username var.

**Comment by benrudolph** [comment]
hey @sravfeyn that's a good example of how to create a user globally. since that info in sensitive we don't store it in the ansible repo itself. we have a `dev.yml` (https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/vars/dev.yml#L67) that shows you what that file looks like. on `salt` and `india6` you can modify the `india.yml` in the config dir in order to set those localsettings variable. happy to offline with you if you need me to point you to it

**Comment by benrudolph** [comment]
just curious what the status of this is? is there a potential bug if the ucr user isn't in the prod database?

**Comment by sravfeyn** [comment]
hey thanks for pinging ben. I haven't prioritized this as it wasn't as urgent. But I am planning to do it once bunch of ICDS things settle down.

**Comment by benrudolph** [comment]
Sounds good, thanks

**Comment by dannyroberts** [comment]
Did we end up needing this, or should we close?

**Comment by sravfeyn** [comment]
Also got done in a different way, so closing this one.

**Pull request closed without merging**
