### PR TITLE
Fix shared dirs in proxy config files

### PR DESCRIPTION
**Pull request by millerdev**
@benrudolph @dannyroberts @emord

### CODE REVIEW

**Comment by benrudolph** [comment]
:+1: , does `--check` on prod return empty now?

**Comment by millerdev** [comment]
I did not try that, but I will...

**Comment by millerdev** [comment]
I tested on staging and zambia, which each have different values for `shared_drive_enabled`

**Comment by millerdev** [comment]
Close to empty. I think fine as far as this PR is concerned. Messaging you offline with changes that I observed.

**Pull request merged**
