### PR TITLE
Move services dir

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts @gcapalbo

### CODE REVIEW

**Comment by dannyroberts** [comment]
What's the idea for this change? Just cleanup or to fix a specific issue?

**Comment by czue** [comment]
https://github.com/dimagi/commcare-hq/pull/10756 I think

**Comment by dannyroberts** [comment]
Ah, thanks!

**Comment by benrudolph** [comment]
this is OK to merge. deployed to india and prod and staging. need to wait for a deploy to zambia and swiss, but then will get to them

**Comment by dannyroberts** [comment]
wee!

**Pull request merged**
