### PR TITLE
pg fixes

### PR DESCRIPTION
**Pull request by snopoke**
@calellowitz

### CODE REVIEW

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by calellowitz** [comment]
looks good. systems without a standby will no longer be able to run the new backup scripts, but i those are only installed on standby machines now anyway. if thats fine by you happy to merge.

**Comment by snopoke** [comment]
These are just inventories for local testing so no backups necessary.

**Comment by calellowitz** [comment]
:+1:

**Comment by emord** [comment]
> systems without a standby will no longer be able to run the new backup scripts

@calellowitz Seems bad for monoliths like swiss? Or is there some other backup process they're following

**Comment by calellowitz** [comment]
@emord
currently our monoliths dont have any backup process so this change wont affect them per se. It just means they will need a different snapshot strategy than we use on prod.

**Pull request merged**
