### PR TITLE
remove apache role

### PR DESCRIPTION
**Pull request by snopoke**
@nickpell

### CODE REVIEW

**Comment by benrudolph** [comment]
i was also considering doing this, but i don't think zambia is off of apache yet. we may want to keep it around until we do that switch? don't have that strong of opinions on it though

**Comment by snopoke** [comment]
wow you're right, crazy. Fine to leave it for now.

**Comment by czue** [comment]
wow, good catch. sorry about the bad advice

**Comment by benrudolph** [comment]
seems like this is OK to merge now

**Comment by czue** [comment]
nice

**Pull request merged**
