### PR TITLE
log cache status to timing log

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@snopoke maybe I missed it—what's the motivation behind logging the cache status? From the docs, $upstream_cache_status seems to refer to whether it went on to make a request to "upstream" (django web workers in our case?) or just returned from the cache. Is that right?

**Comment by dannyroberts** [comment]
Ah, probably related to this email excerpt:

> We did do some changes last time which makes nginx cache the app updates so they don't hit Django as much. This should help dramatically.

**Comment by snopoke** [comment]
@dannyroberts correct, we now use nginx caching for app downloads so this would allow us to monitor how well it's working.

**Comment by snopoke** [comment]
Here's the PR where we introduced that: https://github.com/dimagi/commcare-hq/pull/17171

**Pull request merged**
