### PR TITLE
do not encourage storing vault password in a plaintext file

### PR DESCRIPTION
**Pull request by dannyroberts**
use `--ask-vault-pass` instead of `--vault-password-file`

changed in the `ap`/`aps` aliases and in the README

### CODE REVIEW

**Comment by benrudolph** [comment]
looks good! unfortunately with security comes inconvenience 😞

**Comment by snopoke** [comment]
Downvoted just cause it sucks to have to enter 2 passwords - but agree with the logic

**Comment by dannyroberts** [comment]
:( I wonder if there's a way to move SUDO pass into the (vaulted) passwords file instead of `--ask-sudo-pass` then we'd be back to one password, and the sudo password would be encrypted

**Comment by snopoke** [comment]
No real need. I was just complaining.

**Comment by dannyroberts** [comment]
It's actually pretty easy, I just tested it out. Any objection to me making that change? All I have to do is add

```
ansible_sudo_pass: <I'm not going to put it here>
```

to `vars/${ENV}/${ENV}_vault.yml` (which is encrypted of course) and remove `--ask-sudo-pass` from `ap`.

**Comment by snopoke** [comment]
Yea I guess that's fine as long as we have password auth off for ssh logins
which we do. Nice.

**Comment by dannyroberts** [comment]
https://github.com/dimagi/commcarehq-ansible/pull/485

**Pull request merged**
