### PR TITLE
update couchdb role for service script

### PR DESCRIPTION
**Pull request by emord**
adds https://github.com/emord/ansible-couchdb-cluster/commit/826df6010e191f17c35be598e9e4ba79d538c47f

@dimagi/scale-team 

buddy @orangejenny

### CODE REVIEW

**Comment by benrudolph** [comment]
nice. do you know if it will retry after a period? or does this pretty much mean we'll have to bring up couch on restart?

**Comment by emord** [comment]
@benrudolph that's something we'll need to solve elshwere in our stack. like after ecryptfs is run.

Right now we also have to start ES psql and riak manually

**Comment by emord** [comment]
```
root@pillow1:~# service couchdb2 start
couchdb2 could not start because data directory does not exist
```
I've never been so excited for a database to fail to start

**Comment by gcapalbo** [comment]
haha, nice!

**Pull request merged**
