### PR TITLE
add environment hosts mapping to localsettings

### PR DESCRIPTION
**Pull request by snopoke**
@TylerSheffels

### CODE REVIEW

**Comment by TylerSheffels** [comment]
Out of curiosity, what is this used for?

**Comment by snopoke** [comment]
It's used to figure out which hosts pillowtop is (so that we can connect to
the supervisor RPC server)

**Comment by dannyroberts** [comment]
Really nice and simple!

**Comment by snopoke** [comment]
Yea, better than adding Ansible dependency and reading inventory file which
is what I had originally.

On 11 September 2015 at 16:59, Daniel Roberts <notifications@github.com>
wrote:

> Really nice and simple!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcarehq-ansible/pull/208#issuecomment-139568434>
> .
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
You mean like https://github.com/dimagi/commcare-hq/blob/47b9c07d5c67c6ea54a280f3b217a0d749489660/fab/fabfile.py#L280-280? I guess that's a little different since that only adds an ansible dependency to the machine you're using to deploy.

**Comment by snopoke** [comment]
Yea, that's fine. Also there you don't have the luxury of having ansible
build your localsettings for you.

On 11 September 2015 at 17:45, Daniel Roberts <notifications@github.com>
wrote:

> You mean like
> https://github.com/dimagi/commcare-hq/blob/47b9c07d5c67c6ea54a280f3b217a0d749489660/fab/fabfile.py#L280-280?
> I guess that's a little different since that only adds an ansible
> dependency to the machine you're using to deploy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcarehq-ansible/pull/208#issuecomment-139581140>
> .
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Pull request merged**
