### PR TITLE
allow groovy scripts on ES

### PR DESCRIPTION
**Pull request by snopoke**
@esoergel @TylerSheffels

### CODE REVIEW

**Comment by snopoke** [comment]
Already run on prod

**Comment by benrudolph** [comment]
:v: groovy. looks good, i know in the past we've just restarted ES. what's the advantage here of shutting down the pillows and doing these extra steps?

**Comment by benrudolph** [comment]
(just saw your other PR with the explanation)

**Comment by snopoke** [comment]
Yea, if you just restart all the nodes then any ES functions on HQ are basically down (error).

**Comment by TylerSheffels** [comment]
:+1: Based on the number of retries + timeout on each one, this potentially runs a really long time. I don't think this is necessarily a bad thing, e.g. just set it running then do something else but it might make for a really long iteration time (although, I assume ES doesn't take all that long to restart).

**Comment by snopoke** [comment]
Yea, this took about 2 mins per server on prod but can definitely take longer with more nodes / shards etc. or if you don't stop the pillows.

**Comment by esoergel** [comment]
Looks good, thanks Simon!

**Comment by czue** [comment]
classic pact being a bummer.

**Comment by czue** [comment]
this is totally baller btw.

**Comment by snopoke** [comment]
:grinning:

**Pull request merged**
