### PR TITLE
Add timing log format and timing to cchq

### PR DESCRIPTION
**Pull request by TylerSheffels**
@dannyroberts 

@snopoke Buddy!

### CODE REVIEW

**Comment by czue** [comment]
neat - does this tell us timing of every request?

**Comment by dannyroberts** [comment]
Yup, and tyler and I mocked up a log parser that users commcare-hq/django's
url resolution to replace urls with the corresponding django view path,
which tyler's taken off with to parse the new timing log:
https://github.com/dimagi/commcare-hq/compare/nginx-logparsing. The
intended product of passing the timing log through this is to answer not
only "which single requests have the longest run time", but also which
views do our workers spend most of their total time processing (i.e. sum of
time of all requests to that view; think long running views that are
frequently called), and for a given view, what's the distribution of run
times (not just the single longest run time).

In particular, I think sorting by total time spent by prod web workers
processing all requests to a view is a good place to start for finding
low-hanging fruit for speedups—good mix of "does it take a long time to
run" and "is this view actually used".

Thoughts?

**Comment by czue** [comment]
:+1: sounds like a good plan to me

**Comment by snopoke** [comment]
Not to say this isn't useful but you can already get that from NewRelic:
https://rpm.newrelic.com/accounts/366142/applications/5058236/transactions

**Comment by czue** [comment]
wow, that does look exactly like what @dannyroberts just described.

**Comment by dannyroberts** [comment]
huh! Well there we go, we should just use that then!

**Comment by TylerSheffels** [comment]
Damn, that is exactly what we were looking for.

**Pull request merged**
