### PR TITLE
Initial travis file

### PR DESCRIPTION
**Pull request by benrudolph**
cc: @czue @esoergel

### CODE REVIEW

**Comment by benrudolph** [comment]
and so the travis sludge begins...

**Comment by czue** [comment]
:eyes:

**Comment by czue** [comment]
what's the end game here? travis deploys to a server?

**Comment by esoergel** [comment]
:angel: build failures, bat:man: !  Does travis run tests on every commit for this repo or is it just 'cause they were pushed individually?

**Comment by benrudolph** [comment]
haha! yeah they were pushed individually. i think the end game here is to have our entire `deploy_stack` run on travis so we know if it works. then we can test certain things about the setup as well. the playbook returns 0 or 1 so it makes a good script for travis testing. was inspired by this [blog post](https://servercheck.in/blog/testing-ansible-roles-travis-ci-github) and @millerdev's pain in getting up and running with ansible.

**Comment by benrudolph** [comment]
:white_check_mark: for now just syntax checking. hopefully we can test more roles in the future. just don't want everyone's branch to show an :x: while i take my time figuring this out

**Comment by TylerSheffels** [comment]
@benrudolph Huge fan of this

**Comment by TylerSheffels** [comment]
Merging so I can get my PR to pass, assuming you will open a new PR for more changes on this branch

**Comment by czue** [comment]
would be amazing if we got this fully working. might find ourselves wrestling with travis's runtime restrictions.

**Comment by snopoke** [comment]
amaze:crystal_ball:s

**Pull request merged**
