### PR TITLE
Use raw and endraw for tf local settings

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke @TylerSheffels https://github.com/dimagi/commcarehq-ansible/pull/272/files#r49047688

### CODE REVIEW

**Comment by TylerSheffels** [comment]
@benrudolph Have you tested this? This thread seems to indicate it might not work like you think:  https://github.com/ansible/ansible/issues/4638

**Comment by benrudolph** [comment]
yikes good catch. no not yet

**Comment by benrudolph** [comment]
seems to work as expected despite that ticket:
screen shot 2016-01-07 at 11 28 29 am

**Comment by benrudolph** [comment]
though that was just with `--check`

**Comment by TylerSheffels** [comment]
looks good enough for me, thanks for checking

**Comment by czue** [comment]
:+1: well that's quite a bit easier to understand

**Comment by tamsky** [comment]
FYI nifty macro can do the same thing:

``` jinja
{# Macro which emits `expr` surrounded by literal double braces that Jinja ignores. #}
{%- macro _ (expr) -%}
  {{ '{{' }}{{ expr }}{{ '}}' }}
{%- endmacro -%}

...
URL_ROOT = "%s/a/{{ _('DOMAIN') }}" % URL_HOST
...
```

**Comment by benrudolph** [comment]
thanks for the tip @tamsky! we're getting rid of this in the end, but will keep it in mind

**Pull request merged**
