### PR TITLE
Default to using postgres

### PR DESCRIPTION
**Pull request by benrudolph**
@wspride @dannyroberts

### CODE REVIEW

**Comment by benrudolph** [comment]
:tada:

**Comment by benrudolph** [comment]
been a long time coming

**Comment by czue** [comment]
nice, is this gonna go out today?

**Comment by benrudolph** [comment]
already did

**Comment by czue** [comment]
nice! (does that mean i should merge?)

**Comment by benrudolph** [comment]
:+1:

**Comment by wpride** [comment]
Haha just got this because I am primarily @wpride but very chill.

**Comment by benrudolph** [comment]
Ah right I got them confused

**Pull request merged**
