### PR TITLE
Redirect to .org

### PR DESCRIPTION
**Pull request by benrudolph**
@TylerSheffels would this work?
cc: @emord @millerdev

### CODE REVIEW

**Comment by TylerSheffels** [comment]
@benrudolph I think you want to do something like https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/nginx/vars/cchq_redirect.yml and https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/deploy_proxy.yml#L16

The downside is that this requires adding a couple variables to the config settings

**Comment by benrudolph** [comment]
thanks for the info. closing for now until i have opportunity to fix

**Comment by benrudolph** [comment]
k should be good, just need to update the variables on salt

**Comment by TylerSheffels** [comment]
@benrudolph You will also need to add in a line in deploy_proxy.yml: 
https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/deploy_proxy.yml#L16

**Comment by benrudolph** [comment]
yep thanks, i strangely woke up last night and that was at the forefront my mind

**Pull request closed without merging**
