### PR TITLE
disable per host keys

### PR DESCRIPTION
**Pull request by snopoke**
This allows us to run ansible tasks without having to
ssh into the Vagrant control machine.
https://docs.ansible.com/ansible/guide_vagrant.html

@calellowitz @millerdev @benrudolph

### CODE REVIEW

**Comment by millerdev** [comment]
Cool! FWIW, it was already possible to run ansible tasks from the host machine (using your own SSH keys for auth) if `PUBKEY=~/.ssh/id_rsa.pub reset-vms` was used to provision the VMs.

**Comment by snopoke** [comment]
cool, didn't know that. `reset-vms` doesn't work for me at all (syntax
different of xargs between mac and linux I think). Also this relies on the
provisioning scripts working which also don't for me.

**Comment by millerdev** [comment]
can't merge

**Comment by snopoke** [comment]
updated

**Pull request merged**
