### PR TITLE
add deploy_control.yml to set up ansible control machine

### PR DESCRIPTION
**Pull request by dannyroberts**
currently just adds users and installs editors

### CODE REVIEW

**Comment by dannyroberts** [comment]
**for salt machine**

```bash
# provide 'ansible' user's password
ENV=production && ansible-playbook -u root -i inventories/localhost deploy_control.yml -e "@../config/$ENV/$ENV.yml" --ask-sudo-pass
```

**for indiacloud6**
```bash
# provide 'ansible' user's password
ENV=india && ansible-playbook -u root -i inventories/localhost deploy_control.yml -e "@../config/$ENV/$ENV.yml" --ask-sudo-pass
```

**Comment by dannyroberts** [comment]
@czue ran this on salt machine, want to give india a go?

**Comment by czue** [comment]
@dannyroberts it got most of the way through it but then failed with this error:

```
TASK: [users | Add dev group] ************************************************* 
fatal: [localhost] => sudo output closed while waiting for password prompt:
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `HIPAA_USERS' already defined near line 5 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `HIPAA_ACTOR' already defined near line 6 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `APACHE' already defined near line 8 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `PACKAGES' already defined near line 9 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `GIT' already defined near line 10 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `PYTHON' already defined near line 11 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `CHOWN_CONF' already defined near line 12 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `CHMOD_CONF' already defined near line 13 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `MV_CONF' already defined near line 14 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `UPSTART' already defined near line 15 <<<
sudo: >>> /etc/sudoers.d/cchq_sudoers: Alias `HQCOMMANDS' already defined near line 17 <<<
sudo: parse error in /etc/sudoers.d/cchq_sudoers near line 5
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin


```

**Comment by dannyroberts** [comment]
hmm, I don't recognize that error. I'll revisit it shortly

**Comment by benrudolph** [comment]
I got that error once when I accidentally did `sudo -iu salt bash` on the india control machine

**Comment by dannyroberts** [comment]
Ah, thanks @benrudolph

**Comment by TylerSheffels** [comment]
I just rebased this and ran it on both salt and india control machines.  I think its probably good to go.  Cory's error looks like a badly formatted sudoers file, but I don't see that anywhere.

**Comment by TylerSheffels** [comment]
@dannyroberts @czue

**Comment by czue** [comment]
i'll let @dannyroberts review/merge

**Comment by dannyroberts** [comment]
Oh lol that's what I'd thought I'd already done this before!

**Comment by dannyroberts** [comment]
Thanks @TylerSheffels

**Pull request merged**
