### PR TITLE
more pillows for processing cases

### PR DESCRIPTION
**Pull request by snopoke**
@dimagi/scale-team

### CODE REVIEW

**Comment by snopoke** [comment]
I see kafka only has 24 case-sql partitions so we can't have more than 24 processes reading from it

**Comment by snopoke** [comment]
I've added 12 more partitions to `case-sql` topic brining total to 36

**Comment by snopoke** [comment]
@czue I'm basing them off stats in the (Change Feed Dashboard on DD](https://app.datadoghq.com/dash/256236/change-feeds?live=true&page=0&is_auto=false&from_ts=1513930533574&to_ts=1513934133574&tile_size=m&tpl_var_env=icds-new&fullscreen=false)

And the system load for the VMs

**Comment by emord** [comment]
fwiw I don't think we saw any help when we moved from 8 to 12. My guess is that we're limted by ES. more shards would mean we could index more quickly and we may be limited by only having 5

**Pull request merged**
