### PR TITLE
add git ppa

### PR DESCRIPTION
**Pull request by benrudolph**
@esoergel gonna be using this branch to test out git version upgrade after reading the release notes

cc: @czue

### CODE REVIEW

**Comment by esoergel** [comment]
Cool, does this use the latest git 2.x?

**Comment by benrudolph** [comment]
looks like 2.5.2: https://launchpad.net/~git-core/+archive/ubuntu/ppa. though we can (and maybe should) pin it to a version

**Comment by benrudolph** [comment]
ok did some research. i don't think we have anything to worry about. going to run it on staging. really the only git commands that get run on a production machine are the deploy ones. the only bwds incompat changes are git push and git add and the changes are an edge case.

**Comment by benrudolph** [comment]
k this works and submodules properly update with the staging deploy optimization. we can merge this, let staging sit for a bit just to make sure and then run this on prod, india, and zambia and merge then merge this PR: https://github.com/dimagi/commcare-hq/pull/8234

**Comment by czue** [comment]
:+1: from me but will wait for you to remove label

**Comment by benrudolph** [comment]
👍

**Comment by esoergel** [comment]
Nice!  I wanna see the before and after timings on these changes.

**Comment by benrudolph** [comment]
Yea definitely, we're already approaching a 15 minutes deploy

**Pull request merged**
