### PR TITLE
Localsettings tags

### PR DESCRIPTION
**Pull request by benrudolph**
@emord as discussed. if it looks ok, i'll notify the team so people are aware

cc: @mkangia

### CODE REVIEW

**Comment by emord** [comment]
so localsettings is everything and now there's hq- settings to only deploy those? that looks good to me

**Comment by benrudolph** [comment]
that's correct

@dimagi/team-commcare-hq fyi if you deploy `localsettings` it will now also update formplayer and touchforms. This is so they get proper machine updates when machines change. If you want to only deploy hq localsettings, use the `hq-localsettings` tag

**Comment by millerdev** [comment]
@benrudolph what does this mean for a person who doesn't know much about formplayer and touchforms? Should we just continue to deploy `localsettings` and not worry about the fact that it's doing more than just `localsettings`? Or is `hq-localsettings` the new common case, and we should only deploy `localsettings` in special cases?

**Comment by emord** [comment]
@millerdev I think usually formplayer settings should not change, or it should be obvious why they change. If it's not there's a backup for deploying a subset of these changes (like hq-localsettings)

this came up because I deployed localsettings to NIC but not formplayers. As a result formplayer was authenticating against couch 1 instead of couch. so I think this change is strictly better so things like that don't happen again

**Pull request merged**
