### PR TITLE
Add motech

### PR DESCRIPTION
**Pull request by TylerSheffels**
Adds a motech reverse proxy for: http://manage.dimagi.com/default.asp?175901#edit_0_175901

@dannyroberts

### CODE REVIEW

**Comment by dannyroberts** [comment]
@TylerSheffels check out https://gist.github.com/dannyroberts/83cd9bd00f8c396c6b61 + Tampermonkey for some awesomely clean fogbugz URLs 4 Life!

**Comment by czue** [comment]
lol

**Comment by TylerSheffels** [comment]
Would like to point out I have that beautiful script installed, but happened to be editing the ticket when I copied the url.

**Comment by dannyroberts** [comment]
ah fair

**Pull request merged**
