### PR TITLE
fix up fp settings for icds

### PR DESCRIPTION
**Pull request by benrudolph**
@sravfeyn @javierwilson fixes some settings for formplayer. still needs to be tested

### CODE REVIEW

**Comment by benrudolph** [comment]
@javierwilson there's a mail host in these settings that is set to `relay.nic.in` however that is not the same setting as `localsettings.EMAIL_SMTP_HOST`. wondering if that discrepancy was intentional

**Comment by javierwilson** [comment]
not intentional, i think django should always use localhost. then all mail routing should be taken care by the machine.

**Comment by emord** [comment]
Added open for review until after your testing is complete

**Comment by benrudolph** [comment]
cool ran this and it's good 2 go

**Pull request merged**
