### PR TITLE
pip to upgrade supervisor

### PR DESCRIPTION
**Pull request by benrudolph**
@millerdev @snopoke going to try and upgrade supervisord and see if it helps with deploy errors revolving around weirdness in supervisor. our version is 3 years old (3.0b2). seems like they've made a fair number of bug fixes since: http://supervisord.org/changes.html. will go through breaking changes and do staging upgrade first

### CODE REVIEW

**Comment by benrudolph** [comment]
the change log also mentions performance improvements to starting and stopping lots of processes (aka pillowtop!)

**Comment by millerdev** [comment]
should we test this out for a while (few days) on staging first before merging and deploying to production?

**Comment by benrudolph** [comment]
Yep definitely

**Comment by benrudolph** [comment]
Brain dumping so I remember where I was:
1. Install new version of supervisor with `pip`. Gets stored in `/usr/local/bin`
2. Remove apt version of supervisor. stored in `/usr/bin`
3. Redeploy upstart conf with proper supervisor path
4. Shut down all supervisor processes. Shutdown supervisord
5. Start supervisord back up with new process
6. Run `--tags=users` to update sudoers files

**Pull request closed without merging**
