### PR TITLE
add more groups to dog stream

### PR DESCRIPTION
**Pull request by benrudolph**
@czue

### CODE REVIEW

**Comment by czue** [comment]
:+1:

**Comment by benrudolph** [comment]
fyi, now up and [running](https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1446501357550&to_ts=1446504957550&tile_size=xs&exp_metric=couch.timings&exp_scope=&exp_agg=avg&exp_row_type=metric&exp_group=couch_url)

**Comment by czue** [comment]
:heart_eyes: 

I was messing around with this and the sum of time is a pretty interesting metric for view "hotness". I assume there's no way to filter based on the aggregated threshold in datadog right? (I couldn't find it)

**Comment by czue** [comment]
([I think I figured this out](https://app.datadoghq.com/screen/39150/couch-health))

**Comment by benrudolph** [comment]
wow that board is super interesting

**Pull request merged**
