### PR TITLE
Add postgres log rotation

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke @TylerSheffels Adding postgres log rotation. went to debug some postgres stuff the other day and `ls` took minutes to run because there are so many files in there

### CODE REVIEW

**Comment by benrudolph** [comment]
deployed this to staging, but not prod yet. will wait for review

**Comment by snopoke** [comment]
Much needed, will do a closet look tomorrow

**Comment by TylerSheffels** [comment]
Looks great to me, and with daily rotation I don't think there is a need for a size limit.

**Comment by TylerSheffels** [comment]
@benrudolph Assuming that you will deploy this to prod and india

**Comment by benrudolph** [comment]
yep will do. also i think postgres has its own sizing limit

**Pull request merged**
